ci:
  autofix_commit_msg: "🔨 refactor: [pre-commit.ci] auto fixes from pre-commit.com hooks"
  autoupdate_commit_msg: "🤖 ci(pre-commit): pre-commit autoupdate"

repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: "0.7.21"
    hooks:
      - id: mdformat
        types: [markdown]
