name: Create build tools
on: [push, workflow_dispatch]

jobs:
  create-tools-macos:
    name: Create build tools for macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install homebrew for Apple silicon and Rosetta
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        shell: zsh {0}

      - name: Setup shell
        run: |
          echo "alias brow='arch --x86_64 /usr/local/Homebrew/bin/brew'" >> ~/.zshrc
          echo "source scripts/brew-switch.zsh" >> ~/.zshrc
          echo "source scripts/brow-switch.zsh" >> ~/.zshrc
        shell: zsh {0}

      - name: Install python
        run: |
          source ~/.zshrc
          brew-switch python@3.13 3.13.0_1
          brow-switch python@3.13 3.13.0_1
        shell: zsh {0}
