name: Create build resources
on: [workflow_dispatch]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-resources-macos:
    name: Create build resources for macOS
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install homebrew for Apple silicon and Rosetta
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        shell: zsh {0}

      - name: Setup shell
        run: |
          echo "alias brow='arch --x86_64 /usr/local/Homebrew/bin/brew'" >> ~/.zshrc
          echo "source macos/scripts/brew-switch.sh" >> ~/.zshrc
          echo "export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1" >> ~/.zshrc
          echo "set -o allexport" >> ~/.zshrc
          echo "source macos/.env" >> ~/.zshrc
        shell: zsh {0}

      - name: Create new branch
        run: |
          git checkout -b update-build-resources
          git fetch origin

      - name: Install python
        run: |
          source ~/.zshrc
          brew-switch $BREW_PYTHON_FORMULA $BREW_PYTHON_VERSION
          brew link --overwrite $BREW_PYTHON_FORMULA
        shell: zsh {0}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify python
        run: |
          source ~/.zshrc
          ./macos/scripts/check_python_mac.py
        shell: zsh {0}

      - name: Install deps needed to build resources
        run: |
          source ~/.zshrc
          brew install libb2 ncurses
          brow install gettext libb2 ncurses xz mpdecimal sqlite
          pipx install delocate wheel
          /opt/homebrew/bin/python3 -m pip install python-dotenv --break-system-packages
        shell: zsh {0}

      - name: Create build resources
        run: |
          source ~/.zshrc
          ./macos/scripts/create-build-resources.sh
        shell: zsh {0}

      - name: Commit build resources
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ./macos ./logs
          git commit -m "🔨 refactor: generate build resources" || exit 0
          git push origin update-build-resources --force
          gh pr create --base main --head update-build-resources --title "🔨 refactor: generate build resources" --fill
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
